[project]
name = "automated-report-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chardet>=5.2.0",
    "crew>=0.9.2",
    "crewai>=0.165.1",
    "crewai-tools>=0.62.3",
    "pandas>=2.3.1",
]
